name: Bug Report
description: Report a bug in InitRunner
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: role-yaml
    attributes:
      label: Role YAML snippet
      description: If relevant, paste your role YAML (redact any secrets).
      render: yaml

  - type: textarea
    id: error-output
    attributes:
      label: Error output
      description: Paste any error messages or tracebacks.
      render: shell

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      options:
        - "3.11"
        - "3.12"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Docker
    validations:
      required: true

  - type: input
    id: initrunner-version
    attributes:
      label: InitRunner version
      description: "Output of `initrunner --version`"
      placeholder: "1.4.1"
    validations:
      required: true
