app = "initrunner"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  INITRUNNER_HOME = "/data"

[processes]
  app = "initrunner --help"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50

[[mounts]]
  source = "initrunner_data"
  destination = "/data"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
